name: wam-model
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - tk
  - numpy
  - pandas
  - scipy
  - networkx
  - pillow
  - geopandas
  - pyogrio
  - shapely
  - pyproj
  - gdal
